name: CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
  workflow_dispatch:
    inputs:
      target:
        description: "Target job to run"
        type: choice
        options:
          - all
          - format-check
          - build-and-test
          - sanitizer-tests
          - lint
        required: false
        default: "all"

jobs:
  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'format-check' || github.event.inputs.target == 'all'
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Check formatting
        run: ./scripts.sh format-check

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'build-and-test' || github.event.inputs.target == 'all'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang clang-tidy

      - name: Build
        run: ./scripts.sh clean build

      - name: Run tests
        run: ./scripts.sh test

  sanitizer-tests:
    name: Sanitizer Tests
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'sanitizer-tests' || github.event.inputs.target == 'all'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang

      - name: Build with Address Sanitizer
        run: ./scripts.sh sanitize address

      - name: Run tests
        run: ./scripts.sh test small-only

      - name: Build with Undefined Behavior Sanitizer
        run: ./scripts.sh sanitize undefined

      - name: Run tests
        run: ./scripts.sh test small-only

      - name: Build with Leak Sanitizer
        run: ./scripts.sh sanitize leak

      - name: Run tests
        run: ./scripts.sh test small-only

  lint:
    name: Static Analysis (clang-tidy)
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.target == 'lint' || github.event.inputs.target == 'all'
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang-tidy

      - name: Run linter
        run: ./scripts.sh lint
